baseURL: "/"
title: E5C Analytics
theme: bigspring-hugo-startup-theme
paginate: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: 'UA-135279366-1'
markup:
  goldmark:
    renderer:
      unsafe: yes
