######################## default configuration ####################
baseURL = "https://e5canalytics.com/"
title = "E5C Analytics"
theme = "bigspring"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-135279366-1" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true